name: Debian Build Bot
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      ref:
        required: true

jobs:
  version:
    name: Get versions
    runs-on: ubuntu-latest
    outputs:
      ocis: ${{ steps.version.outputs.ocis }}
      ref: ${{ steps.version.outputs.ref }}
      epoch: ${{ steps.version.outputs.epoch }}
    steps:
      - id: version
        run: |
          if [ -n "${{ github.event.inputs.ref }}" ]; then
            TAG=${{ github.event.inputs.ref }}
          else
            TAG=${{ github.ref_name }}
          fi
          DATE=`curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/owncloud/ocis/releases/tags/${TAG}" | jq -r ".created_at"`
          echo "ocis=${TAG#v}" >> $GITHUB_OUTPUT
          echo "ref=${TAG}" >> $GITHUB_OUTPUT
          date -d "${DATE}" +epoch=%s >> $GITHUB_OUTPUT
  build:
    name: Build ${{ matrix.config.d_arch }} packages
    runs-on: ubuntu-24.04-arm
    # runs-on: ${{ matrix.config.host }}
    container:
      image: debian@sha256:c94f5ddd41327aa2d4a7cfba7889056c02936182fd76a513fec6160c97181fc0
      # image: ${{ matrix.config.host_image }}
    strategy:
      matrix:
        config:
          - d_arch: amd64
            c_arch: x86_64-linux-gnu
            h_arch: amd64
            go_arch: amd64
            go_host_arch: amd64
            host: ubuntu-24.04
            host_image: debian@sha256:38a76d01668772e381ad2826d876627c89e7133e2f8a0f5d567306798b0f2a16
          - d_arch: arm64
            c_arch: aarch64-linux-gnu
            h_arch: arm64
            go_arch: arm64
            go_host_arch: arm64
            host: ubuntu-24.04-arm
            host_image: debian@sha256:c94f5ddd41327aa2d4a7cfba7889056c02936182fd76a513fec6160c97181fc0
          # - d_arch: i386 #        Not reproducible
          #   c_arch: i686-linux-gnu
          #   h_arch: amd64
          #   go_arch: 386
          #   go_host_arch: amd64
          #   host: ubuntu-24.04
          #   host_image: debian@sha256:38a76d01668772e381ad2826d876627c89e7133e2f8a0f5d567306798b0f2a16
          - d_arch: armhf
            c_arch: arm-linux-gnueabihf
            h_arch: arm64
            go_arch: arm
            go_host_arch: arm64
            go_arm: 7
            host: ubuntu-24.04-arm
            host_image: debian@sha256:c94f5ddd41327aa2d4a7cfba7889056c02936182fd76a513fec6160c97181fc0
          - d_arch: armel
            c_arch: arm-linux-gnueabi
            h_arch: arm64
            go_arch: arm
            go_host_arch: arm64
            go_arm: 5
            host: ubuntu-24.04-arm
            host_image: debian@sha256:c94f5ddd41327aa2d4a7cfba7889056c02936182fd76a513fec6160c97181fc0
          - d_arch: loong64
            c_arch: loongarch64-linux-gnu
            h_arch: arm64
            go_arch: loong64
            go_host_arch: arm64
            host: ubuntu-26.04-arm
            host_image: debian@sha256:c94f5ddd41327aa2d4a7cfba7889056c02936182fd76a513fec6160c97181fc0
          - d_arch: ppc64el
            c_arch: powerpc64le-linux-gnu
            h_arch: arm64
            go_arch: ppc64le
            go_host_arch: arm64
            host: ubuntu-24.04-arm
            host_image: debian@sha256:c94f5ddd41327aa2d4a7cfba7889056c02936182fd76a513fec6160c97181fc0
          - d_arch: riscv64
            c_arch: riscv64-linux-gnu
            h_arch: arm64
            go_arch: riscv64
            go_host_arch: arm64
            host: ubuntu-24.04-arm
            host_image: debian@sha256:c94f5ddd41327aa2d4a7cfba7889056c02936182fd76a513fec6160c97181fc0
          - d_arch: s390x
            c_arch: s390x-linux-gnu
            h_arch: arm64
            go_arch: s390x
            go_host_arch: arm64
            host: ubuntu-24.04-arm
            host_image: debian@sha256:c94f5ddd41327aa2d4a7cfba7889056c02936182fd76a513fec6160c97181fc0
    needs: version
    steps:
      - name: Prepare source and build scripts
        run: |
          apt-get update
          apt-get install -y --no-install-recommends ca-certificates curl jq gpg
          curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -o ocis_${{ needs.version.outputs.ocis }}.orig.tar.gz \
              https://github.com/owncloud/ocis/archive/refs/tags/${{ needs.version.outputs.ref }}.tar.gz
          tar xvf ocis_${{ needs.version.outputs.ocis }}.orig.tar.gz
          curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -o ocis-debian.tar.gz \
              https://github.com/${{ github.repository }}/archive/${{ github.ref }}.tar.gz
          tar xvf ocis-debian.tar.gz --strip-components=1 -C ocis-${{ needs.version.outputs.ocis }} ocis-debian-`echo "${{ github.ref_name }}" | sed 's/^v//'`/debian
      - name: Prepare and build
        working-directory: ocis-${{ needs.version.outputs.ocis }}
        env:
          GOPROXY: "https://proxy.golang.org"
          C_ARCH: ${{ matrix.config.c_arch }}
          D_ARCH: ${{ matrix.config.d_arch }}
          H_ARCH: arm64
          # H_ARCH: ${{ matrix.config.h_arch }}
          NODE_VERSION: 24.x
          GOHOSTOS: linux
          GOHOSTARCH: arm64
          # GOHOSTARCH: ${{ matrix.config.go_host_arch }}
          GOOS: linux
          GOARCH: ${{ matrix.config.go_arch }}
          SOURCE_DATE_EPOCH: ${{ needs.version.outputs.epoch }}
        run: |
          tar xf ../ocis-debian.tar.gz ocis-debian-`echo "${{ github.ref_name }}" | sed 's/^v//'`/.github/workflows/.extras.sh -O | sh
          if [ -n "${{ matrix.config.go_arm }}" ]; then export GOARM="${{ matrix.config.go_arm }}"; fi
          export CC=${C_ARCH}-gcc
          export CXX=${C_ARCH}-g++
          dpkg-buildpackage -v${{ needs.version.outputs.ocis }}-1 -us -uc -Zgzip -a ${D_ARCH}
      - name: Send built packages - src
        uses: actions/upload-artifact@v7
        if: matrix.config.d_arch == 'amd64'
        with:
          name: src
          retention-days: 1
          path: |
            ocis_${{ needs.version.outputs.ocis }}.orig.tar.gz
            ocis_${{ needs.version.outputs.ocis }}-1.debian.tar.gz
            ocis_${{ needs.version.outputs.ocis }}-1.dsc
      - name: Send built packages - all
        uses: actions/upload-artifact@v7
        if: matrix.config.d_arch == 'amd64'
        with:
          name: all
          retention-days: 1
          path: |
            ocis-common_${{ needs.version.outputs.ocis }}-1_all.deb
      - name: Send built packages - ${{ matrix.config.d_arch }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.config.d_arch }}
          retention-days: 1
          path: |
            ocis_${{ needs.version.outputs.ocis }}-1_${{ matrix.config.d_arch }}.deb
            ocis-dbgsym_${{ needs.version.outputs.ocis }}-1_${{ matrix.config.d_arch }}.deb
  repository:
    name: Generate Debian repository and upload all artifacts
    needs: [version,build]
    runs-on: ubuntu-24.04
    steps:
      - name: Get tools
        run: sudo apt install --no-install-recommends dctrl-tools moreutils
      - name: Checkout code to get previous tag
        uses: actions/checkout@v7
        with:
          fetch-depth: '0'
      - name: Get previous tag and create target directory
        id: previous
        run: |
          PREVIOUS_TAG=`git describe --abbrev=0 --tags ${{ needs.version.outputs.ref }}^`
          echo "ref=$PREVIOUS_TAG" >> $GITHUB_OUTPUT
          mkdir -p download/${{ needs.version.outputs.ref }}
      - name: Download previous Packages (if exists)
        uses: robinraju/release-downloader@v1
        continue-on-error: true
        with:
          tag: ${{ steps.previous.outputs.ref }}
          out-file-path: download/${{ needs.version.outputs.ref }}
          fileName: 'Packages.gz'
      - name: Download previous Sources (if exists)
        uses: robinraju/release-downloader@v1
        continue-on-error: true
        with:
          tag: ${{ steps.previous.outputs.ref }}
          out-file-path: download/${{ needs.version.outputs.ref }}
          fileName: 'Sources.gz'
      - name: Download artifacts from build jobs
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: download/${{ needs.version.outputs.ref }}
      - name: Generate Packages, Sources, and InRelease
        working-directory: download/${{ needs.version.outputs.ref }}
        run: |
          gzip -d Packages.gz
          gzip -d Sources.gz
          apt-ftparchive packages ../../download/${{ needs.version.outputs.ref }} | sort-dctrl -k Package,Architecture | tee -a Packages
          apt-ftparchive sources ../../download/${{ needs.version.outputs.ref }} | tee -a Sources
          sort-dctrl -k Version:v,Package,Architecture Packages | sponge Packages
          sort-dctrl -k Version:v Sources | sponge Sources
          gzip -n -9 Packages
          gzip -n -9 Sources
          echo "${{ secrets.GPG_KEY }}" | gpg --batch --import
          PUB=`curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/owncloud/ocis/releases/tags/${{ needs.version.outputs.ref }}" | jq -r ".published_at" | date -u -R -f -`
          apt-ftparchive release -o APT::FTPArchive::Release::Date="${PUB}" . | gpg --batch --yes --clearsign --local-user ${{ secrets.GPG_KEY_FINGERPRINT }} --output - | tee InRelease
      - name: Upload all artifacts
        uses: actions/upload-artifact@v7
        if: github.ref_type != 'tag'
        with:
          name: repo
          retention-days: 1
          path: download/${{ needs.version.outputs.ref }}/**
      - name: Upload all files to release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: download/${{ needs.version.outputs.ref }}/**